import type { Metadata } from "next";
import { Noto_Sans, Noto_Sans_Mono, Noto_Sans_Gujarati } from "next/font/google";
import "./globals.css";

const notoSans = Noto_Sans({
	variable: "--font-sans",
	subsets: ["latin"],
	fallback: ["sans-serif"],
	display: "auto",
	preload: true,
});

const notoSansMono = Noto_Sans_Mono({
	variable: "--font-mono",
	subsets: ["latin"],
	fallback: ["sans-serif"],
	display: "auto",
	preload: true,
});

const notoSansGujarati = Noto_Sans_Gujarati({
	variable: "--font-gujarati",
	subsets: ["gujarati"],
	fallback: ["sans-serif"],
	display: "auto",
	preload: true,
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${notoSans.variable} ${notoSansMono.variable} ${notoSansGujarati.variable} antialiased`}
		>
			<body>{children}</body>
		</html>
	);
}
